# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - consiguetutrabajoapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Delete Artifacts
        # You may pin to the exact commit or the version.
        # uses: jimschubert/delete-artifacts-action@5e12816fde69c33b3374ee9d14d0e97137064bce
        uses: jimschubert/delete-artifacts-action@v1
        with:
          # GitHub token used to access the repository defined in the GITHUB_REPOSITORY input.
          GITHUB_TOKEN: ${{github.token}}
          # The target github repo in the format owner/repo
          GITHUB_REPOSITORY: ${{github.repository}}
          # A specific Actions run identifier. You can use this to specify the current run and do some post-run cleanup.
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'consiguetutrabajoapi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_10552469C39E4912A94FA5D1D451A475 }}
          package: .
